長い文章を書く人のためにアウトラインプロセッサの基本をまとめてみた
http://readingmonkey.blog45.fc2.com/blog-entry-750.html のまとめ
 

* 長い文章を書く人のためにアウトラインプロセッサの基本をまとめてみた

** 要約

- 長い文章を書くにはアウトラインプロセッサが便利

- アウトラインプロセッサは、

  - 文章の論理構造

  -（執筆中に直面する）文章の複雑さ・長さ

  の両方を、書き手が随時コントロールしながら執筆するための道具

- アウトラインプロセッサを使うと〈今できるところから〉書くスタイルがと
  りやすい

- 《発想》《構成》《剪定》の作業を分けると効率が良い

** 話の流れ

- 何故この世界にアウトラインプロセッサなんてものが存在するのか

- アウトラインプロセッサが何をもたらすのか

- アウトラインプロセッサを使って書く実際の作業プロセスの一方法について

** アウトラインプロセッサとは？

　辞書的に言えば、アウトラインプロセッサとは、文章の構成（アウトライン）の組立てや章･節の構成･変更を容易にする機能を備えた文書作成支援ソフトウェアである。
　英語ではoutlinerという呼称が一般的である。

　以下ではまず、アウトラインプロセッサならば必ず登載されている^{※}基本機能について説明しよう。

*** 章や節や段落などを階層化されたブロックとして扱える

    アウトラインプロセッサでは、インデント（字下げ）を使って、文章の部
    分部分をひとかたまりのブロックとして扱い、ブロック同士を階層化でき
    る。
    
    例えば、章タイトルのブロックに下位項目としていくつかの節タイトルを
    従属させたり、節タイトルに下位項目としていくつかの段落を従属させる
    ことができる。

**** ブロックごとに表示したり隠したりできる

このご利益は、文章の構造（アウトライン）だけをみたり、細部を表示したりできること

この機能によって、長く複雑な文章のうち、必要に応じて現在検討中の範囲
やレベル（だけ）を表示し編集することができる。

言い換えれば、複雑で長い文章を書く際、執筆者が取り扱える限度に、常に
複雑さや長さをコントロールできる訳である。

**** ブロック単位での編集が容易

普通のテキストエディタやワープロの文書編集機能に加えて、ブロック単位
でのコピー・移動・階層移動が行える。

**** ブロック単位でのコピー

** アウトラインプロセッサを使うメリット

では、こうしたアウトラインプロセッサの機能は文章作成に何をもたらすだろうか？

*** 構成（アウトライン）先行の文章作成

文章作成の他の作業から構成づくりを取り出すことで、構成の作成・変更の作
業を軽くし、文章作成全体の作業を軽減することになる。

- 構成づくり自体は、最初から完成形の文章を書き始めることに比べれば、は
  るかに時間も労力も少なくて済む。

　構成は、単語・フレーズのレベルで可能である。

- 全体を一望できる

- また単語レベルで構成を考えると、つなぎ言葉など前後の文脈を規定する言
  葉は除かれ、位置・階層レベルを変えるだけで各項目の関係を組み直せる。

*** 文章構成の一望化

文章作成の全過程で、文章の構成を念頭において作業することが容易になる。

ブロック単位での表示・隠し機能を使うことで、全体の構成を俯瞰したり、細
部に集中したりといった切替えが自在にできる（文章のズームアウト／クロー
ズアップ）ので、《過度の複雑さのために構成》の作業が混乱・停滞する危険
を減らす。

またインデントにより構造化しつつ書くことになるので、常に何が文章の幹で
あり何が枝であるかが明確であり、また明確化することを求められる。すなわ
ち文章の論理構造を自覚的に取り扱うことになり、そのトレーニングにもなる

アウトラインプロセッサを使うことで、構成づくりの作業のはじめからおしま
いまで、論旨の迷走や構成の破綻が起こりにくくし、起こった場合にも修正が
できるだけ容易にできるように支援する。　

*** 発想と構成の分離

発想と構成の作業を分離することを助ける。

この二つを分離すべき理由は次の通りである。

- 発想（思いつき）を促進するためには、できるだけ制約条件を外し、判断す
  ること・結論を出すことを控えるべきである。

- 構成はこれとは逆に、たとえば章・節・段落・文の包括（上下）関係や前後
  関係などを制約条件として、考慮に入れておこなわざるを得ない。文章の各
  部分は互いに依存し合い制約し合うから、このことは必然である。

- 正反対の志向を持つ２種類の作業は、できれば分離して行った方が互いに邪
  魔し合う弊害が減じる。

- アウトラインプロセッサによる文章作成では、順序や階層レベルの変更を簡
  単にブロック単位でできることから、まず思いつくだけ書き出す（発想の作
  業）、しかる後、並べかえる（構成の作業）ことに専念する、といった作業
  の分離が行いやすい。

*** 〈今できるところ〉から着手する

アウトラインプロセッサは、人を最初から順番に書くことから解放し、〈今で
きるところ〉から文章書きの作業に着手／再開することを支援する。

　最初に全体の構成を考えて書くこと自体、文章を順番に書くことからの逸脱
だったが※、文章を構成する部分を発想することも、それを並べ替えて構成を
つくることも、粗い構成を細分化していくことも、それらを最終的に文章化す
ることも、どれも文章の順序どおりに行う必要はない。

　アウトラインプロセッサを使った文章作成では、文章の構成要素を階層化さ
れたブロックとして扱うといったが、その階層はいつでも並べ替え・組替えが
可能であり、また容易である。あとでいくらでも順番を変えることができるも
のして文章を書いていくのだから、「最初から順番に書く」ことに拘泥するの
は無意味である。

　また、最初に全体構造を組み立てることから始めたが、アウトラインプロセッ
サを使っていれば、どれだけ書き進んでも最上位の章立てレベル以外を隠して、
全体構造が一望できたところにいつでも何度でも戻ることできる。

　自分が書き出した込み入った文章に言葉のジャングルか迷路のように迷いだ
したら、いつでも上空から迷路全体を俯瞰することだってできる。

　つまるところ、すでに大まかな構成はできているのだから（そして大まかな
構成をやり直すことだっていつでもできるのだから）、好きなところ書きやす
いところから書いていっても、どこにも行き着かず迷走することはない。


** アウトラインプロセッサを使った文章作成のプロセス


　アウトラインプロセッサを使った文章作成は、次の三つのパートに分かれる。

- アウトラインづくり
- アウトラインの剪定
- 文章化

実際は、この３つを行ったり来たりすることになる（長い文章ほど往復する回
数は多くなる。今回の文章程度だと２往復くらい）。　

*** アウトラインづくり

アウトラインづくりは、基本的にトップダウンの作業となる。

まず全体の構成をつくり、それを細分化・詳細化していくことで、アウトライ
ンを成長させていく。　

**** 最上位レベル

- 既存の形式に従がう

- 書きたいことと書くべきことを箇条書きする

　したがって、既存のフォーマットを使うにしろ使わないにしろ、何を書こうとするのか、書き手であるあなたが決めなくてはならない。

　そして、○○について書こうと決めたら、今度はそのためにどんなことを書かなくてはならないかについても考えなくてはならない。

　書きたいこと（want to write:WTW）と書くべきこと（need to
write：NTW）は、アウトラインの必須項目である。

　既存のフォーマットは文章のおおまかな順序や構造を与えてくれるだけでなく、空白を書き手に差し出すことで、書きたいこと（WTW）と書くべきこと（NTW）を呼び出す呼び水となるものである。
　
　《発想》と《構成》の作業を分けて行う基本ルールに従って、まずは書きたいこと（WTW）と書くべきこと（NTW）を、思いつく限り書き出してみよう。

　長い文で書いてしまうと取り回しが悪い。

　この段階では、やや言葉足らずでかまわないから、単語かフレーズの形で思いつきを書き並べていく。もちろん順序は問わない。

　書きたいこと（WTW）と書くべきこと（NTW）以外に浮かんできたものも、とにかく書き出そう。

　現時点で不明なこと、書くに当たっての懸念、その他、書くべきでないことや、とくに書く必要でないことも出てくるに違いない。

　にごった井戸を澄んだ水が出てくるまで汲み上げるようなもので、無駄に思えるものを外に出した後に、採用すべき思いつきが出てくることも少なくない。
　
　書き出せるだけだしたら、軽く分類するなり、既存のフォーマットに当てはめるなりすれば、スタート地点としての最上位レベルのアウトラインは、とりあえずできたことになる。
　

　なお、不要にみえる項目も削除せず、（ゴミ箱）という項目をつくってその下位項目として移動しておくことをお勧めする。

　最終稿の中に生かされなくても（そして一見まぬけに見えても）、こうしたジャンク項目はひそかに書き手の知性と動機付けの水位を上げてくれているのだ。
　
　
**** 細分化の作業

ここまで着たら、大まかな項目が箇条書きとして並んでいるはずである。それ
ぞれの項目を細分化・詳細化していくことで、アウトラインを成長させていく。

大原則は〈今できるところから〉行うである。

細分化・詳細化:

- 詳細化は、項目によって難易の差が大きい。向こう見ずに最難関から突破し
  ようとせず、最も取り組みやすそうなところから手をつけることを勧める。
  　
- 今の時点ではぼんやりとしか分かっていない／考えていない事項について、
  より詳しく何であるのかを突き止め、議論を詳細化し深めていく

- つまり、いま詳細化しようとしている項目を「問い」として捉えて、その答え
  を、下位項目として追加していくのである。

- そうしてでてきた下位項目についても問答を行い、さらに下位項目を追加して
  いく。

この繰り返しでアウトラインの細分化を行っていく。

どのような問答を行うべきかは、書いている文章やアウトラインの段階によっ
て様々だが、よく使われる問いを並べてみると以下のようになる。

- 「～とは何か？」－本質：定義を導く
- 「言い換えると？」－説明・言い換えを導く
- 「具体的には？」－説明・事例を導く
- 「どんな例があるか？」－例示を導く
- 「何故そう言えるのか？」－根拠を導く
- 「その後は？」ー帰結・結果を導く

作業の進め方は、最上位レベルでやったのと同様、《発想》と《構成》の作
業をを分けて行うのがいい。

- まず《発想》の作業では、ここでも思いつく限りとにかく書き出していく。

- 導きの問いを参考に、今のアウトラインの各項目に問いを投げかけ、あるい
  は問いの形にして、答えらしきものが浮かぶ限り書き出す。

- 先に言ったとおり、無関係くさいものも、同考えてもハズレな答えも、とに
  かく書き出してしまった方がいい。

- うまい答えが出ないからと止まってしまうと、自分の中の検閲官に追いつか
  れてしまい、効率は落ちてしまう。

- そうした自己検閲をなるべく避けるために、《発想》と《構成》の作業を分けるのである。　

- 問答の答えを書き出し終えたら、《構成》の作業として、新たに書き並んだ
  下位項目をしかるべき順に並べ替え、不要な項目を削除せずゴミ箱項目に移
  し、作業中に他にも必要な項目が思い浮かべば追加していく。

　
細分化は、何重にも繰り返す必要がある。

- 一通りやり終えた後に、最初に手をつけた項目を見直すと、さらに細分化を
  続ける必要に気付くことがある。

- 詳細化する過程で、書き手の理解が進み思考が深まったのである。言うまで
  もなく、この細分化の作業が、アウトラインづくりの中心であり、最も時間
  がかかるところである。　

*** アウトラインの剪定


**** アウトラインづくりは必ず行き詰る


　アウトラインづくりは、基本的にトップダウン、全体構成から細部へ進む作業になるが、そうそう一直線に下っていけば完成するものではない。
　
　大抵の場合、アウトラインが詳細になっていくと、どこかで行き詰ってしまい先に進まなくなる。
　たとえばいくつもの筋や要素が入り組んで見通しが極めて悪くなったり、本筋が何であるかが見えにくくなる。
　
　また手がける文章が長ければ長いほど、細部が出来上がってくると、最初に決めた全体構成のところどころに不整合や改善点が見えてくる事が多い。
　全体構成を決めたときには、文章を構成する細かい要素の隅々まで念頭において考えられた訳ではない。アウトラインを細分化する中で素材や構成と格闘しているうちに、そうした細部が持つ意味が見えてきたり、他の要素とのつながりが発見できることは少なくない。
　最初は必須に思えた要素がそれほど重要ではなくなくなったり、繰り返しが過ぎてうるさく感じるようになったり、不要部分や重複部分も目に付いてくる。
　もちろんすべての重複部分や不要部分を取り除けば済む訳ではない。冗長性のない文章は、踊り場のない階段のようなもので、読みづらく、かえって伝えるべきものを伝えにくくなる。
　
　重要なのは、この行き詰まりは、最初の目論見が甘かったことだけから生じているのではないことだ。
　今のあなたは、かつてのあなたと同じではない。あなたの知力は、このアウトラインに取っ組み合うわずかの間に、いくらか成長したのだ。だからこそ弱点に目が行き、改善すべき点に意識が向く。

　書くことは気付きを生む。
　人は理解したことを書くばかりでなく、理解するためにも書く。
　あるいは最初の理解を乗り越えるために書くのだとも言える。
　そうでなければ、今も書かれている多くの見返りのない文章は書かれぬままだっただろう。
　だから、これは良い徴候だ。つまり、ようやく本当に頭で考えることができる段階に来たということだから。
　
　細分化を進めてアウトラインが育ち切ったら（そしてアウトラインの繁茂が道をふさぎ出したら）、全体を見直す機会である。
　
　
**** 剪定の作業


　樹木の剪定とは異なり、アウトラインの剪定は、取り除くだけではなく増補する必要も同じくらいある（アウトラインは樹木とは違い自力では成長しない）。
　それでもあえて剪定の比喩を使うのは、木の枝葉に近づきハサミを使った後、木から離れて全体像を見ることで成果を確認する、という作業が、ここでのアウトラインを整える作業に似ているからである。
　削除したり増補したりした後、その成果を評価するには、より広い範囲を見ながら行わなければならない。
　つまりアウトラインを整理する作業は、より上位の項目のレベルや全体構成のレベルにまで、繰り返し戻って確かめることが必要になる。
　
　上位レベルを参照しながら、次のようなことを確認する。
論理的に破綻してないか？

前後関係に問題はないか（まだ出てこない事項を参照したり前提にしていないか）？

重複した部分はないか？→あればどれを生かすべきか？一方を「何章を参照せよ」にするか？複数生かすなら表現を変えるか？

不要な部分はないか？→省略できないか？本文ではなく注記に回すか？


　こうしたことを確認しながら、アウトラインに対して移動と除去と追加を行っていく。

　
**** 大きな変更が必要な場合

　部分的な手直しでは足りず、章立ての順序を入れ替えたり、一つの章を分割したり、また複数の章を合体したり、と大きく構成を変える必要が出てくるかもしれない。

　書かれている内容が同じでも、構成が変わると（順序の変更のようなものですらも）、文章はまるで異なったものになる。

　今まで手を掛けて育ててきたアウトラインほど、下手に手を入れたら台無しになりはしないか、と手を出しづらくなる。
　

　対策はいろいろあるが、一番簡易なのは、先のバージョンのアウトラインはまるごと残しておくことだ。

　こうしておけば、安心していくらでもいじり回すことができる。

　いじり倒してうまく行かなかったら、うまくいかなかったバージョンとして、それも残しておく。
　

　最終的にボツになるアウトラインにも、後で役立つヒントが含まれることがある。

　失敗をもたらした大胆な改造は、少なくともその時点では、少なくとも意図においては、採用すべきものがあったはずである。それを消してしまっては、心理的に、その良き意図ごと捨ててしまうことになる。

　失敗バージョンを残しておいた方が、あとでその意図をもっとうまく実現する成功バージョンが生まれやすい。
　
　
**** 煮詰まったら違うフォーマットに変換してみる

　アウトラインプロセッサは、基本的にコンピュータの上で文書作成が完結するように作られたツールである。

　しかしユーザーはそれに縛られる必要はない。

　作業途中の文章がコンピュータの中にあるとつい忘れがちだが、ひどく行き詰ったら、あるいはいろいろ改変を試みてもうまくいかなかったら、手をつかって紙に構成を書き出してみるだけでも、思わぬ展望が開けたりする。

　箇条書きでもいいし、項目同士を線で結んでチャート化してもいい。表にまとめてみるのもいい。

　あるいは音声言語を使って誰かに概要を説明してみるのもよい。
　


*** 文章化の作業

細分化と剪定を経て、アウトラインが十分に熟したら、単語レベルから完全な
文・文章のレベルへ移行する段階である。

ここでも〈今できるところから〉着手する原則に従う。　

いきなり最終稿を作ろうとするより、ドラフト（下書き）のそのまたドラフト
（下書き）を書くぐらいの感じで進めた方がスムーズに進み、手直しも案外少
なくて済む。

文章化してみることで、改めてアウトラインの過不足や順序の問題に気付くこ
とも多い。文章化を進めるうちに構成を変える必要はどうしても出てくる。
アウトラインづくり, アウトラインの剪定の段階にまで戻ってやり直すべきである。

《発想》《構成》《剪定》の作業をもう一度行うことになる。

大規模に変更する場合は特に、やり直した方が結局速く済む。


