* 批判的思考について

** 動機

   情報の量が多く早く変化する時代，自分だけの考えにとらわれない，人の考
   えをやみくもに受け入れない，柔軟な考え方を手に入れたいと思っている。

   批判的思考はそんな思いにヒントを与えてくれそうに思った。


** 良き市民のための批判的思考 (原著）

   - サイト :: [[http://www.google.co.jp/url?sa=t&rct=j&q=&esrc=s&source=web&cd=5&ved=0CFIQFjAE&url=http%3A%2F%2Fwww.psych.or.jp%2Fpublication%2Fworold_pdf%2F61%2F61-5-8.pdf&ei=s-iSUpCfLYXMkQW0gIHQAQ&usg=AFQjCNF2otqcdNRl2uU1aQb2hYXQ1t0I0g&sig2=2brut6KaJ1kC4ZNpBD4xyQ&bvm=bv.56988011,d.dGI][良き市民のための批判的思考]]
   - 著者 :: 京都大学大学院教育学研究科教授   楠見　孝

** 批判的思考とは（参考にしたサイトとまとめ)

*** [[http://ja.wikipedia.org/wiki/%E6%89%B9%E5%88%A4%E7%9A%84%E6%80%9D%E8%80%83][批判的思考-Wikipedia]] 

    [[https://www.dropbox.com/s/lir8vmrzehlrrlp/suzuki-%E6%89%B9%E5%88%A4%E7%9A%84%E6%80%9D%E8%80%83%E3%81%AE%E6%A6%82%E8%A6%81.pdf][批判的思考-Wikipediaの概要]] (dropbox) 
    
*** [[http://www.educ.kyoto-u.ac.jp/cogpsy/personal/Kusumi/hihan.htm][批判的思考-楠見]] のまとめ

**** 定義

     批判的思考は, 
     - 推論の規準(criteria)にしたがう，論理的で偏りのない思考である。

     批判的思考は, 
     - 人の話を聞いたり，文章を読んだり,議論をしたり，自分の考えを述べ
       る時に目標指向的に働く。

     - したがって，日常語である“相手を批判する”思考という狭い意味では
       ない。

     - むしろ，自分の推論過程を意識的に吟味する反省的な思考であり，何を
       信じ，主張し，行動するかの決定に焦点を当てる思考である。

**** 批判的思考の構成要素

批判的思考の能力（評価の規準でもある）は，つぎのように分けることができる。

- 基礎的な明確化 :: 明確化のための基礎的能力としては，

  - 1)焦点化によって，問題，仮説，主題を明確化すること，

  - 2)論証を分析すること(構造，結論，理由など)，

  - 3)明確化のための疑問(なぜ？　なにが重要か？事例は？など)を提起すること－－がある。

- 推論の基盤の検討 :: 推論を支える情報源としては，他者の主張，観察，以
     前におこなった推論の結論がある。そこで，

  1. 情報源の信頼性を判断したり (例：専門家によるものか？　情報源間一致
     度は？　確立した手続きをとっているか？)，

  2. 観察や観察報告を評価する能力が必要である。

- 推論 :: 推論には，演繹の判断(クラス論理学，条件式，命題の解釈など)，
          帰納の判断，価値判断(背景事実，結果，選択肢，バランス，ウエイ
          ト，決定などの判断)の能力が関わる。帰納における判断には，

  1. 一般化(データの典型性，網羅範囲の限界，サンプリング)の能力と，

  2. 探索的な結論や仮説を推論する能力がある。後者には，調査(証拠と反証，
     説明の探索)をしたり，仮説や結論の合理性を規準(事実の説明における無
     矛盾性，もっともらしさなど)にてらして判断することを含む。

- 推論後の明確化 :: 推論後の明確化には，

  - 1)名辞や定義(同義・分類・範囲
    などの形式，定義の方法，多義の同定と扱い，内容など)を判断する能力と，
  - 2)(複数の論証を検討，精緻化することによって)仮説を同定する能力が関わ
  る。

- 方略 :: 批判的思考の最終段階として，行為の決定(問題の定義，解決の判断
          のための規準の選択，他の解決策の形成，何をすべきかの仮の決定，
          状況全体を考慮した上での再吟味，実現のモニターなど)がある。こ
          れらはメタ認知的活動である。一方，他者との相互作用を，議論，
          発表，論文などを通しておこなうことも大切である。ここには，こ
          れまで述べてきた(a)-(d)のすべての能力が関わる。


　批判的思考は，(a)-(e)で述べてきた能力だけでは，十分に発揮されない。態度（傾向性）が，問題解決や読解，討論などの状況において必要である。
　批判的思考者がもつ態度（傾向性）には，
　１)明確な主張や理由を求めること
　２)信頼できる情報源を利用すること
　３)状況全体を考慮する，重要なもとの問題とずれないようにする
　４)複数の選択肢を探す
　５)開かれた心をもつ(対話的思考，仮定に基づく思考など)
　６)証拠や理由に立脚した立場をとる
－－などがある。



** 良き市民のための批判的思考 (まとめ）

*** 批判的思考とは相手を非難すること？

**** 批判的思考において大切なこと

1. 相手の発言に耳を傾け，証拠や論理，感情を的確に解釈すること，

2. 自分の考えに誤りや偏りがないかを振り返ることである。

相手の発言に耳を傾けずに挙げ足を取ることは批判的な思考と正反対のことがらである。

**** 批判的思考（クリティカルシンキング）の定義

1. 証拠に基づく論理的で偏りのない思考

2. 自分の思考過程を意識的に吟味する省察的（リフレクティブ）で熟慮的思考

3. より良い思考を行うために目標や文脈に応じて実行される目標指向的な思考

**** 批判的思考の例

批判的思考は，学業，職業など幅広い場面で働く汎用的（ジェネリック）スキ
ルでもある。

***** 学習者，研究者

批判的に読む・聞く（情報収集），話す（討論やプレゼンテーション），書く
（レポートや論文）ことを行っている。

学問・研究のために必要なコミュニケーション能力（学問・研究リテラシー）
を支えるスキルである。

大学の初年次教育で重視されるようになってきた。

***** 日常生活や職業生活においては，

テレビを見る，広告に接する，インターネットで情報を集める，決定する時な
どに批判的思考は働いている。

情報を鵜呑みにせず立ち止まって考える批判的思考は，市民としての生活に必
要なコミュニケーション能力（市民リテラシー）を支えている。


*** 批判的思考のプロセスは？

**** 四つの段階

1. 情報を明確化する（報道，発言，書籍などの主張とそれを支える根拠を正し
   くとらえる）

2. 推論をするための土台を検討する（隠れた前提を明らかにしたり，主張が信
   頼できる証拠に基づいているかを検討する），

3. 推論を行う（演繹・帰納・価値判断によって，偏りのない結論を論理的に
   導く），

4. 意思決定や問題解決をする。

**** メタ認知プロセス

これら四つに加えて，1から4が正しく行われているかを振り返り（モニター），
コントロールするのが1 段階高いレベルにあるメタ認知プロセスである。

メタ認知プロセスは，目標に照らして批判的思考を実行するかどうかの判断も
している（田中・楠見，2007）。

**** 批判的思考態度
さらに，こうした批判的思考のプロセスを土台から支えているのが，批判的に
考えようとする態度である。

批判的思考態度には，

1. 論理的に考えようとすること，
2. 証拠に基づいて考えようとすること，
3. 多くの情報を探究しようとすること，
4. 偏見や先入観にとらわれず客観的に考えようとすること（平山・楠見,
   2004），
5. そしてこれらすべてに関わる，熟慮することがある。


*** 今なぜ批判的思考が必要とされるのか？

**** 第1. 市民に批判的思考が求められている

市民はテレビや新聞をはじめ，インターネット，家族，友人などを通して，さ
まざまな情報の中で，信頼できる情報を判断して行動をする必要がある。

- とくに東日本大震災以後，低線量の放射能による健康影響に関しては，批判
  的思考と知識によって，リスクに立ち向かい，リスクを減らす適切な行動を
  し，科学的根拠のない偏見や差別をなくすことが必要である。

- また，今後の日本のエネルギー問題を考える際にも，一人ひとりがさまざま
  な情報を批判的に吟味して判断することが大切である。

楠見・三浦・小倉（2012）は，東日本大震災の原発事故による放射線リスク情
報の理解に批判的思考態度がどのように影響するかについて，被災県，首都圏，
関西圏の計1752 人の一般市民を対象に，震災半年後と1 年後にネット調査を行っ
た。その結果，批判的思考態度はメディアリテラシーを向上させることを通し
て，知識や自発的な情報収集を促進し，リスク対処行動に影響を及ぼしていた
ことがわかった。

**** 第2  社会で働く人に批判的思考が求められている

急速に変化する社会や経済の状況に対応するために，単なる知識だけではなく
て，批判的思考能力を中核とした，論理的思考力，コミュニケーション能力を
もつ人材が求められるようになってきている。

「大学生が卒業までに最低限身につけなければならない能力」としての学士力
の位置づけは，そのあらわれでもある。学士力には，①知識・理解，②汎用的
スキル（論理的思考力，コミュニケーションスキル，情報リテラシーなど），
③態度・志向性，④統合的な学習経験と創造的思考力―の四つが挙げられてい
る（中央教育審議会, 2008）。

批判的思考は，汎用的スキルの中核となり，他の三つにも関わる。また，経済
産業省（2007）は「職場や地域社会で多様な人々と仕事をしていくために必要
な基礎的な力」である社会人基礎力として，三つの能力（考え抜く力，前に踏
み出す力，チームで働く力）を挙げている。この中で考え抜く力には，課題発
見力，計画力，創造力を挙げている。これらは，学士力と重なる部分があるが，
より実践的な課題解決に重点が置かれている。

また，働く人が批判的思考態度をもつことは，仕事の経験を省察して，経験か
ら学習する態度を促進する。それは，実践的知識の獲得を通して熟達者になる
ための土台になっている（金井・楠見, 2012）。

**** 第3. 学習者に批判的思考が求められるようになった

- 大学の大衆化によって，入学者に対する学習スキル教育の重要性が高まった。
  そして，導入教育の一環として，ライティング，リーディング，プレゼンテー
  ションなどに関わる批判的思考教育が行われるようになった。これは米国で
  盛んになり，そして日本においてもはじまりつつある（たとえば，楠見・田
  中・平山, 2012）。

- さらに，専門教育（とくに看護教育，経営大学院など）においても，高度の
  知識やスキルを土台にした批判的思考力をもった専門家の育成が重視される
  ようになってきている。

- 小中高生に対しても，社会の変化に対応できるように，「すべての子どもに，
  課題解決のために自ら考え判断・行動できる社会を生き抜く力の育成」が日
  本再生のための鍵と捉えられている（文部科学省, 2012）。そこでは，考え
  る力（クリティカルシンキング）やコミュニケーション能力等の育成に焦点
  が当てられている。

- 小学校から大学までの批判的思考教育を，体系的に行うためには，児童・生
  徒の批判的思考態度や批判的学習スキルが，学年によってどのように発達す
  るか，どのような学習活動が影響を及ぼすのかを明らかにする必要がある。
  さらに，批判的思考の教授法，教材，測定ツールの開発も必要である。


*** 批判的思考研究における心理学の役割とは

**** 批判的思考の源流

古代ギリシャのソクラテスの哲学にさかのぼることができる。「無知の知」の
考え方は，知らないことを自覚する知性に着目したものである。

**** 省察的思考

20 世紀に入って米国のプラグマティズム哲学者デューイは, 「省察的思考」と
して「信念や知識を，それを支える根拠とそこから導出される結論に照らして，
能動的，持続的，慎重に考慮する思考」と定義している。これは現代の批判的
思考の中核となる概念である。

**** 誤謬アプローチに基づく批判的思考教育

1950 年代後半頃からは，日常生活における議論を扱う非形式論理学が盛んになっ
てきた。その流れをくむ誤謬アプローチに基づく批判的思考教育は，議論の形
式的誤謬（後件否定，前件否定など）や非形式的誤謬（過剰一般化，因果関係
の逆転など）を分類して，誤りを起こさないような訓練をするものであり，教
科書も多い。

こうした誤謬について，思考心理学では，古くから形式的・非形式的誤謬に関
するデータを蓄積しており，認知心理学，社会心理学では，直観的ヒューリス
ティックや信念やステレオタイプによるバイアスに関するデータも蓄積してい
る。そして，こうした誤謬やバイアスのデータを示したうえで，これらを克服
する処方的な視点で書かれた教科書とその日本版（Zechmeister & Johnson,
1992 ／道田他訳, 1996-1997）は，日本における批判的思考の教育に大きな影
響を及ぼした。

**** 心理学教育に批判的思考を導入すること

米国では，心理学教育に批判的思考を導入することが積極的に行われ，教科書
だけでなく専門書も複数出版されている。なぜなら，心理学は，人の情報処理
能力に限界があり，記憶，思考，意思決定，社会的認知に誤りやバイアスが生
じうることを実証的に示し，体系的に説明をしている。これらを学生が学ぶこ
とは，日常生活における認知のエラーやバイアスに自覚的になり，それらを修
正することに結びつく。そのほかにも，心理学を通して学ぶ科学的方法論や，
文章の理解や産出，リスク認知，コミュニケーションや流言などのトピックも，
批判的思考に基づく日常生活の実践に役立つと考える。

なお，日本心理学会の教育研究委員会の調査小委員会は，市民，教員を対象に
した調査において，心理学リテラシーと批判的思考態度の関連も調べている
（楠見, 2011b）。その中で，批判的思考態度は，学歴が高いほど高く，また，
心理学学習歴があるほど高くなる傾向があった。これらのことからも，批判的
に考える市民を育てるうえで，大学で学ぶこと，そして心理学を学ぶことの意
義は大きいと考える。


*** 良き市民による幸せな社会とは？

**** 批判的思考能力をもった良き市民を育てること

批判的思考教育の目的の一つは，良き市民を育てることである。良き市民の一
つの形は，批判的思考能力と態度をもち，生活に必要な情報を正しく読み取り，
人に正確に伝え，考えの違う人の意見に耳を傾けつつ適切に行動するというも
のである。そして，責任感をもって，自律的に社会に関わり，倫理的・道徳的
判断を行い，社会的問題を解決する，市民性（シティズンシップ）をもつこと
である。こうした個人が批判的に考えることによって，人生の中で次々と直面
する問題において，より良い決定を積み重ねて，幸福な人生を歩むことができ
ると考える。

私が市民や大学生を対象に実施した複数の調査では，批判的思考態度は，
幸福感とは直接相関はないが，行動を起こし持続する移行モード傾向を通して，
幸福感を高めていることがわかった（楠見, 2012）。また，がんとアトピー性
皮膚炎の患者と家族1089 人に調査したところ，批判的思考態度は，病気への適
応（例：病気についてくよくよと考えない，良くなると信じている）と正の相
関がみられた。そして，パス解析の結果は，批判的思考の態度が科学リテラシー
を高め，病気の知識，食生活の知識を高め，その結果として病気への適応尺度
得点を高めていた（楠見・三浦・小倉，2009）。

**** 批判的に考えるリーダーや専門家を育成する

大学・大学院における批判的思考教育の目的は，批判的に考えるリーダーや専
門家を育成することでもある。

- リーダーらには，市民性と批判的思考に支えられた専門的知識やコミュニケー
  ション能力，そしてリーダーシップをもつことが求められている。

- さらに，現状を省察したうえで将来に目を向け，ビジョンを立て，人々と協
  力して，対立や社会の問題を解決することが重要である。

**** 批判的コミュニティをつくること

しかし，個人レベルでも，社会レベルでも批判的思考を実行することが難しい
ことは事実である。

- 日本の社会では目上の人や仲間に対して批判的思考に基づく発言をしにくい
  のが現状である。

そうした中で必要なことは，まずは身近な家族，学校，職場，地域，ネットと
いったコミュニティにおいて，じっくり考え，対話ができる場（批判的コミュ
ニティ）をつくることである。

- そのためには，必要な情報を自分自身で集め，人に正確に伝え，人の意見に
  耳を傾けることが重要である。

- こうしたコミュニティは社会的問題解決の実践の場である。自分の住むコミュ
  ニティにおける意見や利害関係の対立は，批判的思考のスキルを用いて，相
  手も自分も満足させるような解決を導くことが理想である。

- とくに，自分のもつ認知バイアスを自覚し，多角的な視点で物事を見ること
  によって，異なる価値観や視点を理解する姿勢が大事である。

**** 人生そして社会の問題を協同解決

批判的に考える良き市民が，人生そして社会の問題を協同して解決し，幸せな
人生とより良い社会を築くことができるようになることは一つの理想である。
そのために，心理学者が，批判的思考に関する研究と教育において果たす役割
は大きいと考えている。




** 良き市民のための批判的思考にたいする自分の考え

   以下の点について改めて認識させられた

   - 態度として，メタ認知活動が最も重要であること

     - 曖昧な思考活動を，部分や部品に分けて考えること
     - 自分の考えを第三者的に捉えられること

   - 常に，論理的に考え，判断することを意識する

   協同的批判的コミュニティを形成する難しさについて考えさせられた

   - 他者を信じること？

   - 他者の考え方を知ること？

   批判的思考のための道具として，

   - いまのところ，アウトラインプロセッサがいいと思う

     - 論理的なまとめとレベルが扱える
     - 論理的な流れが書ける
     - 関係が書けると嬉しいが，今はできないかな

   論理だけでなくプロセス（時間経過と考えの変化）も大切なのでは？

   - 論理はスムーズに（一次元的な流れ，文章で）記述できるが，

   - 時間経過による考え方の変化や進化を（関係図で）記述する方法は？










